/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses.$courseSlug'
import { Route as CoursesCourseSlugLessonsLessonSlugRouteImport } from './routes/courses/$courseSlug/lessons/$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseSlugLessonsLessonSlugRoute =
  CoursesCourseSlugLessonsLessonSlugRouteImport.update({
    id: '/lessons/$lessonSlug',
    path: '/lessons/$lessonSlug',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRoute
  '/resources': typeof ResourcesRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRoute
  '/resources': typeof ResourcesRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRoute
  '/resources': typeof ResourcesRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/explore'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/resources'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/explore'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/resources'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/explore'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/resources'
    | '/courses/$courseSlug'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LabsRoute: typeof LabsRoute
  MyLearningRoute: typeof MyLearningRoute
  PathwaysRoute: typeof PathwaysRoute
  ResourcesRoute: typeof ResourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseSlug/lessons/$lessonSlug': {
      id: '/courses/$courseSlug/lessons/$lessonSlug'
      path: '/lessons/$lessonSlug'
      fullPath: '/courses/$courseSlug/lessons/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugLessonsLessonSlugRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
  }
}

interface CoursesCourseSlugRouteChildren {
  CoursesCourseSlugLessonsLessonSlugRoute: typeof CoursesCourseSlugLessonsLessonSlugRoute
}

const CoursesCourseSlugRouteChildren: CoursesCourseSlugRouteChildren = {
  CoursesCourseSlugLessonsLessonSlugRoute:
    CoursesCourseSlugLessonsLessonSlugRoute,
}

const CoursesCourseSlugRouteWithChildren =
  CoursesCourseSlugRoute._addFileChildren(CoursesCourseSlugRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseSlugRoute: CoursesCourseSlugRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LabsRoute: LabsRoute,
  MyLearningRoute: MyLearningRoute,
  PathwaysRoute: PathwaysRoute,
  ResourcesRoute: ResourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
