/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AdminAccessRouteImport } from './routes/admin.access'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as CoursesCourseSlugRouteImport } from './routes/courses.$courseSlug'
import { Route as PathwaysPathwaySlugRouteImport } from './routes/pathways.$pathwaySlug'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as VerifyCertificateNumberRouteImport } from './routes/verify.$certificateNumber'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'
import { Route as CoursesCourseSlugLessonsLessonSlugRouteImport } from './routes/courses/$courseSlug/lessons/$lessonSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/assessments/$assessmentId',
  path: '/assessments/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseSlugRoute = CoursesCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => CoursesRoute,
} as any)
const PathwaysPathwaySlugRoute = PathwaysPathwaySlugRouteImport.update({
  id: '/$pathwaySlug',
  path: '/$pathwaySlug',
  getParentRoute: () => PathwaysRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyCertificateNumberRoute = VerifyCertificateNumberRouteImport.update({
  id: '/verify/$certificateNumber',
  path: '/verify/$certificateNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesCourseSlugLessonsLessonSlugRoute =
  CoursesCourseSlugLessonsLessonSlugRouteImport.update({
    id: '/lessons/$lessonSlug',
    path: '/lessons/$lessonSlug',
    getParentRoute: () => CoursesCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/admin/access': typeof AdminAccessRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/pathways/$pathwaySlug': typeof PathwaysPathwaySlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/admin/access': typeof AdminAccessRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/pathways/$pathwaySlug': typeof PathwaysPathwaySlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/instructor': typeof InstructorRoute
  '/labs': typeof LabsRoute
  '/my-learning': typeof MyLearningRoute
  '/pathways': typeof PathwaysRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sign-in': typeof SignInRoute
  '/admin/access': typeof AdminAccessRoute
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugRouteWithChildren
  '/pathways/$pathwaySlug': typeof PathwaysPathwaySlugRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/verify/$certificateNumber': typeof VerifyCertificateNumberRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/courses/$courseSlug/lessons/$lessonSlug': typeof CoursesCourseSlugLessonsLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/courses'
    | '/explore'
    | '/forgot-password'
    | '/instructor'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/admin/access'
    | '/assessments/$assessmentId'
    | '/courses/$courseSlug'
    | '/pathways/$pathwaySlug'
    | '/projects/$projectId'
    | '/verify/$certificateNumber'
    | '/admin/courses/$courseId'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/courses'
    | '/explore'
    | '/forgot-password'
    | '/instructor'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/admin/access'
    | '/assessments/$assessmentId'
    | '/courses/$courseSlug'
    | '/pathways/$pathwaySlug'
    | '/projects/$projectId'
    | '/verify/$certificateNumber'
    | '/admin/courses/$courseId'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/courses'
    | '/explore'
    | '/forgot-password'
    | '/instructor'
    | '/labs'
    | '/my-learning'
    | '/pathways'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/sign-in'
    | '/admin/access'
    | '/assessments/$assessmentId'
    | '/courses/$courseSlug'
    | '/pathways/$pathwaySlug'
    | '/projects/$projectId'
    | '/verify/$certificateNumber'
    | '/admin/courses/$courseId'
    | '/courses/$courseSlug/lessons/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InstructorRoute: typeof InstructorRoute
  LabsRoute: typeof LabsRoute
  MyLearningRoute: typeof MyLearningRoute
  PathwaysRoute: typeof PathwaysRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SignInRoute: typeof SignInRoute
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  VerifyCertificateNumberRoute: typeof VerifyCertificateNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/assessments/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug': {
      id: '/courses/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/courses/$courseSlug'
      preLoaderRoute: typeof CoursesCourseSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/pathways/$pathwaySlug': {
      id: '/pathways/$pathwaySlug'
      path: '/$pathwaySlug'
      fullPath: '/pathways/$pathwaySlug'
      preLoaderRoute: typeof PathwaysPathwaySlugRouteImport
      parentRoute: typeof PathwaysRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$certificateNumber': {
      id: '/verify/$certificateNumber'
      path: '/verify/$certificateNumber'
      fullPath: '/verify/$certificateNumber'
      preLoaderRoute: typeof VerifyCertificateNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/$courseSlug/lessons/$lessonSlug': {
      id: '/courses/$courseSlug/lessons/$lessonSlug'
      path: '/lessons/$lessonSlug'
      fullPath: '/courses/$courseSlug/lessons/$lessonSlug'
      preLoaderRoute: typeof CoursesCourseSlugLessonsLessonSlugRouteImport
      parentRoute: typeof CoursesCourseSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAccessRoute: typeof AdminAccessRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccessRoute: AdminAccessRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesCourseSlugRouteChildren {
  CoursesCourseSlugLessonsLessonSlugRoute: typeof CoursesCourseSlugLessonsLessonSlugRoute
}

const CoursesCourseSlugRouteChildren: CoursesCourseSlugRouteChildren = {
  CoursesCourseSlugLessonsLessonSlugRoute:
    CoursesCourseSlugLessonsLessonSlugRoute,
}

const CoursesCourseSlugRouteWithChildren =
  CoursesCourseSlugRoute._addFileChildren(CoursesCourseSlugRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseSlugRoute: typeof CoursesCourseSlugRouteWithChildren
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseSlugRoute: CoursesCourseSlugRouteWithChildren,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface PathwaysRouteChildren {
  PathwaysPathwaySlugRoute: typeof PathwaysPathwaySlugRoute
}

const PathwaysRouteChildren: PathwaysRouteChildren = {
  PathwaysPathwaySlugRoute: PathwaysPathwaySlugRoute,
}

const PathwaysRouteWithChildren = PathwaysRoute._addFileChildren(
  PathwaysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InstructorRoute: InstructorRoute,
  LabsRoute: LabsRoute,
  MyLearningRoute: MyLearningRoute,
  PathwaysRoute: PathwaysRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SignInRoute: SignInRoute,
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  VerifyCertificateNumberRoute: VerifyCertificateNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
